server:
  port: 10086        # 端口
spring:
  application:
    name: demo-server      # 应用名称，会在Eureka中显示
eureka:
  instance:       # 注册到服务中心实例的相关信息
    hostname: localhost
  client:
    register-with-eureka: false          # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false         # 是否拉取服务列表，默认是true
    service-url:        # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/demo